# -*- yaml -*-

language: go

env:
  global:
    # Package setup (Ref: http://pkg-go.alioth.debian.org/packaging.html)
    - VERSION="${TRAVIS_TAG:=0.0~git$(date +%Y%m%d)-1}"
    - PKG_URL="https://github.com/suntong/cascadia"
    - PKG_CAT=utils
    - PKG_ARCH=amd64
    - PKG_DESC="Go cascadia package command line CSS selector"
    - PKG_VEND="suntong"
    - PKG_MAINT='Tong Sun <suntong@cpan.org>'
    - PKG_LICNS="MIT"
    # Build time setup
    - TZ=America/Toronto
    - DATE_BUILD=`date -I`

script:
  - date
  - go get -t -v ./...
  - go build -v -ldflags="-X main.date=$DATE_BUILD"
  - cascadia
  - go test -v ./...

  - go get github.com/mitchellh/gox
  - gox -ldflags="-X main.date=$DATE_BUILD" -osarch="linux/386 linux/amd64 darwin/amd64 windows/amd64" -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}"
# linux/386 linux/amd64 linux/arm darwin/amd64 darwin/386 windows/amd64 windows/386
# e.g.: out/cascadia-linux-amd64

before_deploy:
  - gem install fpm --no-document
  - make pkg
  - sed -i -e "s/\$VERSION/$VERSION/" bintray-pkg.json
  - sed -i -e "s/\$DATE/$DATE_BUILD/" bintray-pkg.json

deploy:
  - provider: bintray
    user: suntong
    key: ${BINTRAY_API_KEY}
    file: bintray-bin.json
    skip_cleanup: true

  - provider: bintray
    user: suntong
    key: $BINTRAY_API_KEY
    file: bintray-pkg.json
    skip_cleanup: true
    on:
#      tags: true
